INSERT  INTO
    auto_base_file
      ( 
      id                            
      ,user_id
      ,orgfile_name                           
      ,file_name                            
      ,file_desc
      ,file_savePath
      ,isValid
      ,isUpValid
      ,isDelValid
      ,msg                               
      ,create_name                         
      ,create_date                       
      ,create_by                         
      ) 
values
      (
      :autoBaseFile.id                            
      ,:autoBaseFile.user_id
      ,:autoBaseFile.orgfile_name                          
      ,:autoBaseFile.file_name                        
      ,:autoBaseFile.file_desc
      ,:autoBaseFile.file_savePath
      ,:autoBaseFile.isValid
      ,:autoBaseFile.isUpValid
      ,:autoBaseFile.isDelValid
      ,:autoBaseFile.msg                               
      ,:autoBaseFile.create_name                         
      ,:autoBaseFile.create_date                      
      ,:autoBaseFile.create_by                
      )